alias awszsh="nvim $HOME/.config/zsh/config.d/aws.zsh"
alias ww="nvim $HOME/GitProjects/vimwiki/index.md"
alias fn="cd $HOME/.config/zsh/config.d"
alias lua="nvim $HOME/.config/nvim/lua/bozilla/settings.lua"
alias javalua="nvim $HOME/.config/nvim/ftplugin/java.lua"
alias settings="nvim /mnt/c/Users/Z/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/localstate/settings.json"
